spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: company-service
          uri: lb://company-service
          predicates:
            - Path=/api/companies/**

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true

