spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: company-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/companies/**

        - id: user-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/users/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

